### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Baddest-Juju** [DanaMW/aria2-integration#1]
Noticed this because I was looking at your profile to see if you worked on the uget-integrator project as well. I tried out RossWang's firefox extension (mainly because I was looking for portable solutions and it didn't require the chrome wrapper) and its implementation of AriaNG was very buggy.

Did you fix those issues? If so I'd really like if you packaged this into an xpi. I'd do it myself but the windows version of nodejs/npm you need for packaging is an utter mess.

**Comment by DanaMW** [comment]
I use this on firefox But I installed aria2 myself and run it from uget with the following command line: 
----------------------
--dir=/home/dana/Downloads --enable-rpc=true --rpc-listen-all=true --rpc-allow-origin-all=true --rpc-secret=***** --disable-ipv6 --check-certificate=false --log=/home/dana/.config/.aria2/aria2.log --input-file=/home/dana/.config/.aria2/aria2.session --save-session=/home/dana/.config/.aria2/aria2.session --save-session-interval=180
------------------------------
These are just options I choose you really only need the "rpc" ones to make it work.

You CAN kust go ahead and use the aria2c included with uget, I did at first. As a matter of fact oif uget is running the aria2-integration drops in and works.

**Comment by DanaMW** [comment]
with the editing I did of handlers.json Firefox works pretty good now.

**Comment by Baddest-Juju** [comment]
That's good to hear. Could you package this into an xpi? I'd do it myself but nodejs on Windows is a mess and my Linux box is down.

**Comment by Baddest-Juju** [comment]
I can't install your version of aria2-integration without it being packaged into an .xpi file

Well, I can, with addon debug mode, but it requires I load it in manually every single time I start the browser.

**Comment by DanaMW** [comment]
just download the zip and rename it from *.zip to *.xpi It is not run through mozilla though so you have to use the debugger page in forefox to load it. you should get his if you want ease.

**Comment by DanaMW** [comment]
https://addons.mozilla.org/en-US/firefox/addon/aria2-integration/

**Comment by DanaMW** [comment]
when you set up aria2-integration you have to use backwards slashes in the extension. As if your were in Linux.

**Comment by Baddest-Juju** [comment]
>just download the zip and rename it from *.zip to *.xpi It is not run through mozilla though so you have to use the debugger page in firefox to load it. you should get his if you want ease.

When I do that, Firefox complains the file is corrupt, even with xpinstall.signatures.required set to false. Self-signing is the only way I've ever been able to load unofficial extensions.

**Comment by DanaMW** [comment]
oh hell i forgot to remove the META-INF folder and the key from the manifest.json

**Comment by DanaMW** [comment]
I just got lazy and forgot I guess. Ill do it now.

**Comment by Baddest-Juju** [comment]
Alright but I still think it's going to complain the file is corrupt. Hope I'm wrong.

**Comment by DanaMW** [comment]
You can just use the one on Mozilla it works fine.
https://addons.mozilla.org/en-US/firefox/addon/aria2-integration/

**Comment by Baddest-Juju** [comment]
I'm interested in your version because the one on Mozilla doesn't work fine.

Its AriaNG doesn't properly save Aria2 settings and I generally have to retry several times to get it to connect to the Aria2 server.

Anywho I downloaded your version, extracted it, deleted META-INF, and edited manifest.json to look like this at the bottom:

```
  "icons": {
     "16": "data/icons/16.png",
     "32": "data/icons/32.png",
     "64": "data/icons/64.png",
     "128": "data/icons/128.png",
     "256": "data/icons/256.png"
  },
  "homepage_url": "https://github.com/DanaMW/aria2-integration",
  "options_ui": {
    "page": "data/options/index.html",
    "chrome_style": true
  }
}
```
Then I put it into a zip file with these settings.

![image](https://user-images.githubusercontent.com/33403660/35697285-52f6644e-074f-11e8-8b3f-d56bf0d296c0.png)

I drag and drop it into Firefox, it says the archive is corrupt. I try 'Install Add-on from file', still says it's corrupt. And I know I have signature requirements properly disabled.

![image](https://user-images.githubusercontent.com/33403660/35697364-95a5d040-074f-11e8-9b2d-fa1ce994adda.png)

If I load the folder as a temporary add-on, it works. Doesn't throw a single error. But temporary add-ons have to be loaded every single time you start the browser. So I don't know if you're using an unbranded Firefox (which I believe has even lower security requirements than branded Firefox Developer's Edition) but nothin' I do will let this load normally, unless I'm missing something important.

And I guess I want to know how to get these to load in general, so I can employ the same tactic with other addon forks.

**Comment by DanaMW** [comment]
go to about:debugging at the top you can load an extension but you have to reload it each time you restart.

**Comment by DanaMW** [comment]
Yes sorry was not looking this copy has not been through Mozilla so it is not a valid one yet The link is the valid regularly install able  extension

**Comment by Baddest-Juju** [comment]
Nevermind, I successful got it to load as an xpi file after reverting the change I did to manifest.json where I removed the gecko id. It seems that has to be there.

**Comment by DanaMW** [comment]
Yes I see now sorry I am fixing a client machine and running my two at the same time I am a bit over reaching at the moment lol

**Comment by Baddest-Juju** [comment]
No worries.

**Comment by Baddest-Juju** [comment]
Here's a command that works for both Windows batch and Linux bash. The first bit will create a blank file if none currently exists, otherwise it just appends nothing to the current file.

```cd . >> aria2.session && aria2c --dir=./Downloads --enable-rpc=true --rpc-listen-all=true --rpc-allow-origin-all=true --rpc-secret=!!!j7890!!! --disable-ipv6 --check-certificate=false --log=./aria2.log --input-file=./aria2.session --save-session=./aria2.session --save-session-interval=180```
